#this script performs GO term analysis for all clusters in a DE table generated by differential_expression.R script
#For each cluster, the DE table is filtered with an "intermediate" stringency (avg_log2FC >= 1, p_val_adj < 0.05)

#example usage: 
#Rscript clusterprofiler_intermediate.R --mks ../07_differential_expression/outputs/DAP5/DAP5_level_2_annotation_markers.csv --sample DAP5_level_2_intermediate --wd ."

library(clusterProfiler)
library(Seurat)
library(dplyr)
library(ggplot2)
library(org.At.tair.db) # Annotation package for Arabidopsis
library(enrichplot)
library(readr)
suppressPackageStartupMessages(library(argparse))

#reproducible randomness
set.seed(123)

#getting the args
parser <- ArgumentParser()

parser$add_argument("--mks", help = "path to markers") 
parser$add_argument("--sample", help = "sample name") 
parser$add_argument("--wd", help = "working directory") 

args <- parser$parse_args()

markers <- read_csv(args$mks)

working = args$wd
setwd(working)

outdir <- paste0(args$wd, "/", args$sample)

if (!dir.exists(outdir)) {
  dir.create(outdir, recursive = TRUE)
}

GO_by_cluster <- function(timepoint, clust, markers){
  
  #getting markers for cluster 1
  mark_genes <- filter(markers, cluster == clust) %>% 
    filter(avg_log2FC >= 1) %>% 
    filter(p_val_adj < 0.05) %>%
    pull(gene)
  
  #perform GO enrichment analysis for biological process
  go_results_BP <- enrichGO(
    gene          = mark_genes,
    OrgDb         = org.At.tair.db,
    keyType       = "TAIR",
    ont           = "BP",   
    pAdjustMethod = "BH",
    qvalueCutoff  = 0.05,
    readable      = FALSE
  )
  go_results_BPdf <- as.data.frame(go_results_BP)
  if(nrow(go_results_BPdf)!=0){
    go_results_BPdf$timepoint <- timepoint
    go_results_BPdf$cluster <- clust
    go_results_BPdf$ontology <- "BP"
  }


  #perform GO enrichment analysis for molecular function
  go_results_MF <- enrichGO(
    gene          = mark_genes,
    OrgDb         = org.At.tair.db,
    keyType       = "TAIR",
    ont           = "MF",     
    pAdjustMethod = "BH",
    qvalueCutoff  = 0.05,
    readable      = FALSE
  )
  
  go_results_MFdf <- as.data.frame(go_results_MF)
  if(nrow(go_results_MFdf) != 0){
    go_results_MFdf$timepoint <- timepoint
    go_results_MFdf$cluster <- clust
    go_results_MFdf$ontology <- "MF"
  }
  
  #perform GO enrichment analysis for cellular component
  go_results_CC <- enrichGO(
    gene          = mark_genes,
    OrgDb         = org.At.tair.db,
    keyType       = "TAIR",
    ont           = "CC",     
    pAdjustMethod = "BH",
    qvalueCutoff  = 0.05,
    readable      = FALSE
  )
  
  go_results_CCdf <- as.data.frame(go_results_CC)
  if(nrow(go_results_CCdf)!= 0){
    go_results_CCdf$timepoint <- timepoint
    go_results_CCdf$cluster <- clust
    go_results_CCdf$ontology <- "CC"
  }

  all_go_results <- rbind(go_results_CCdf,
                          go_results_MFdf, 
                          go_results_BPdf)
  
  #plotting, dotplots: 
  pdf(paste0(outdir,"/", args$sample,"_" ,clust, "_dotplots.pdf"))
  if(length(go_results_BP$ID)!= 0){
    plot(dotplot(go_results_BP) + ggtitle("BP GO Enrichment Analysis"))
    
  }
  if(length(go_results_MF$ID)!= 0){
    plot(dotplot(go_results_MF) + ggtitle("MF GO Enrichment Analysis"))
  }
  if(length(go_results_CC$ID)!= 0){
    plot(dotplot(go_results_CC) + ggtitle("CC GO Enrichment Analysis"))
  }
  dev.off()
  
  #plotting, barplots: 
  pdf(paste0(outdir,"/", args$sample,"_" ,clust, "_barplots.pdf"))
  if(length(go_results_BP$ID)!= 0){
    plot(barplot(go_results_BP, showCategory = 20) + ggtitle("BP GO Enrichment Analysis"))
  }
  if(length(go_results_MF$ID)!= 0){
    plot(barplot(go_results_MF, showCategory = 20) + ggtitle("MF GO Enrichment Analysis"))
  }
  if(length(go_results_CC$ID)!= 0){
    plot(barplot(go_results_CC, showCategory = 20) + ggtitle("CC GO Enrichment Analysis"))
  }
  dev.off()
  
  #return table 
  return(all_go_results)

}

clust_go_results <- lapply(unique(markers$cluster), function(x){GO_by_cluster(args$sample, x, markers)})

#combining and saving all GO data
clust_go_results <- do.call("rbind", clust_go_results)
write.csv(clust_go_results, paste0(outdir,"/", args$sample, "_GO_analysis.csv"))

#getting the best GO terms by cluster
clust_go_results %>% group_by(cluster) %>% arrange(p.adjust) %>% dplyr::slice(1) %>% arrange(cluster) %>% 
  write.csv(paste0(outdir,"/", args$sample, "_", "best_GO_terms.csv"))




